List<String> boardSentences = [
  "All the players are on the starting point. The game begins now. 🤡",
  "Eat a spoonful of mustard sauce without any water.",
  "Try to touch your nose with your tongue while hopping on one foot.",
  "Perform 10 consecutive jumping jacks in a public place.",
  "Stand on one leg and try to balance a water bottle on your head for 20 seconds.",
  "Roll your tongue into a U shape and hold it for 10 seconds.",
  "Dance like a Bollywood superstar, imitating a classic dance step from a famous song.",
  "Walk like a crab for 20 steps, sideways with your hands and feet on the ground.",
  "Spin in a circle 10 times and try to walk in a straight line afterward.",
  "Stand on one leg and try to touch your knee to your nose without losing balance.",
  "Hop like a frog from one end of the room to the other.",
  "Balance a spoon on your nose for 20 seconds without using your hands.",
  "Eat one-quarter of an onion without making any facial expressions.",
  "Hop like a frog for 10 steps and other can record the moment.",
  "Sing a popular Bollywood song in a funny voice while acting out the lyrics.",
  "Recite the tongue twister 'Chandu Ke Chacha Ne, Chandu Ki Chachi Ko, Chandni-Chowk Mein, Chandni Raat Mein, Chaandi Ke Chammach Se Chatni Chatai' five times without any errors.",
  "Eat a spoonful of achaar (Indian pickle) and do your best impersonation of a fire-breathing dragon.",
  "Dance like nobody's watching in a crowded area for 30 seconds, incorporating exaggerated and funny movements.",
  "Try to lick your elbow and let other players record your hilarious attempts.",
  "Spin around in circles 10 times and then try to walk in a straight line afterward, imitating a dizzy walk.",
  "Mimic the sound of a different farm animal loudly in a public place every minute for five minutes.",
  "Walk like a penguin for 10 steps, imitating the waddling movement.",
  "Eat a tablespoon of raw garlic without any water.",
  "Hold a full cup of water with your teeth and walk a few steps without spilling.",
  "If you're male: Wear a dupatta (scarf) the way girls wear it and take a selfie with a smooch face. If you're female: Walk like a bodybuilder and strike a few muscular poses.",
  "Hold a plank position for 30 seconds while singing a song of your choice.",
  "Perform the Nagin Dance, imitating the snake-like movements, in front of everyone.",
  "Allow others to write something funny or silly on your forehead with a marker and walk around in public for 30 minutes.",
  "This is the sentence for index 30",
  "This is the sentence for index 31",
  "This is the sentence for index 32",
  "This is the sentence for index 33",
  "This is the sentence for index 34",
  "This is the sentence for index 35",
  "This is the sentence for index 36",
  "This is the sentence for index 37",
  "This is the sentence for index 38",
  "This is the sentence for index 39",
  "This is the sentence for index 40",
  "This is the sentence for index 41",
  "This is the sentence for index 42",
  "This is the sentence for index 43",
  "This is the sentence for index 44",
  "This is the sentence for index 45",
  "This is the sentence for index 46",
  "This is the sentence for index 47",
  "This is the sentence for index 48",
  "This is the sentence for index 49",
  "This is the sentence for index 50",
];
