List<String> boardSentences = [
  "All the players are on the starting point. The game begins now. 🤡",
  "Eat a spoonful of Ketchup.",
  "Touch your nose with your tongue.",
  "Sqeeze lemon in your mouth.",
  "Do 10 push-ups.",
  "Hold a wall sit position for 45 seconds.",
  "Roll your tongue into a U shape.",
  "Perform a classic Bollywood dance step from a famous song.",
  "Walk like a crab for 20 steps, sideways with your hands and feet on the ground.",
  "Spin in a circle 10 times and try to walk a straight line afterward.",
  "Stand on one leg and try to touch your knee to your nose without losing balance.",
  "Hop like a frog from one end of the room to the other.",
  "Balance a spoon on your nose for 20 seconds without using your hands.",
  "Eat one-quarter of an onion.",
  "Hop like a frog for 10 steps.",
  "Sing a popular Bollywood song in a funny voice.",
  "Chandu Ke Chacha Ne, Chandu Ki Chachi Ko, Chandni-Chowk Mein, Chandni Raat Mein, Chaandi Ke Chammach Se Chatni Chatai",
  "Eat a spoonful of achaar (Indian pickle) and do your best impersonation of a fire-breathing dragon.",
  "Dance like nobody's watching in a crowded area for 30 seconds.",
  "Try to lick your elbow and let other players record your hilarious attempts.",
  "Spin around in circles 10 times and try to walk in a straight line afterward.",
  "Mimic the sound of a farm animal loudly in a public place.",
  "Walk like a penguin for 10 steps.",
  "Eat a tablespoon of raw garlic.",
  "Hold a full cup of water with your teeth and walk a few steps without spilling.",
  "If male: Wear a dupatta the way girls wear and have a smooch face selfie. If female: Walk like a bodybuilder and do some poses.",
  "Hold a plank position for 30 seconds while singing a song.",
  "Perform Nagin Dance in front of everyone.",
  "Let others write something on your forehead.",
  "Try to touch your toes without bending your knees.",
  "Wear blindfolds and try to identify the other players by touching their faces.",
  "Arm wrestle with the player on your right and Win.",
  "Do 10 push-ups.",
  "Anyone can give you a task to do. You have to do it. You have only 1 chance.",
  "This is the sentence for index 35",
  "This is the sentence for index 36",
  "This is the sentence for index 37",
  "Thumb wrestle with the player on your left and Win.",
  "",
  "This is the sentence for index 40",
  "Whistle a song and let others guess it correctly. You have 3 chances.",
  "Anyone can give you a task to do. You have to do it. You have only 1 chance.",
  "This is the sentence for index 43",
  "Arm wrestle with the player on your right and Win.",
  "Do ",
  "This is the sentence for index 46",
  "This is the sentence for index 47",
  "Let a player Trace a word on your back and you have to guess the word correctly. You have only 1 chance.",
  "Lick the wall and other can record it.",
  "You have won the Game. Congratulation!",
];
